### ISSUE TITLE
AppLovin Facebook Mediation Crash

### ISSUE THREAD

**Issue by tfkci** [AppLovin/AppLovin-MAX-SDK-Android#130]
```
    implementation("com.applovin.mediation:facebook-adapter:6.8.0.7")
    
     java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at com.facebook.ads.internal.util.common.ANActivityLifecycleCallbacksListener.registerActivityCallbacks(ANActivityLifecycleCallbacksListener.java:70)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:95)
        at java.lang.Thread.run(Thread.java:923)
```
        
After integrating applovin facebook mediation adapter, started to face this error

**Comment by NanaAmoah** [comment]
Hi @tfkci, can you share when this happens ? For example, does this happen when you start the app when we try to initialize Facebook's SDK? Or when you try to load or show an ad? If yes, does this happen with a specific ad format?

**Comment by akshatsingh93** [comment]
Hi,

This is happening on latest SDK version 11.0.1 and causing crash when we have killed the app. i.e when the app is in background.  

**********
    Failed to initialize 3rd-party SDKs. Please make sure to initialize the AppLovin SDK with an Activity context.
**********

```
Attempting to init 3rd-party SDKs without an Activity instance. Please make sure to update the top Activity using `updateActivity().
2022-02-02 15:21:14.921 23742-23975/com.appname E/AndroidRuntime: FATAL EXCEPTION: Thread-14
    Process: com.appname, PID: 23742
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at com.facebook.ads.internal.util.common.ANActivityLifecycleCallbacksListener.registerActivityCallbacks(SourceFile:70)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$a.run(SourceFile:95)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by thomasmso** [comment]
@tfkci / @akshatsingh93 - What SDK version are you on? v11.1.0?

**Comment by tfkci** [comment]
Yes, it is v11.1.0. The crash is hard to localize. Even though we initialize the SDK with the activity context,

`Failed to initialize 3rd-party SDKs. Please make sure to initialize the AppLovin SDK with an Activity context.`

While the app is in the background, it crashes always. The crash occurs for the activity include native ad implementation ( we don't have any clue if the bug is related to the ad unit)

Firebase
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/57030280/152303164-5b50a31b-d9ed-4dd2-9c2c-30f1a856ea03.png">

**Comment by thomasmso** [comment]
Are you able to reproduce this crash locally?

**Comment by thomasmso** [comment]
@tfkci / @akshatsingh93 - Pushed our Facebook adapter v6.8.0.8, can you check if it's fixed?

**Comment by tfkci** [comment]
I can't reproduce the issue for now. Updating now, will share results.

**Comment by tfkci** [comment]
The issue is resolved with v6.8.0.8.

**Comment by NiaNingXue** [comment]
I am using the Facebook adapter v6.8.0.8, but still have the issue. when the application created, I initialize the AppLovin SDK, but if no activity show at the same time, it will crash

**Comment by thomasmso** [comment]
@NiaNingXue - Could you provide full stack trace? And what AppLovin MAX SDK version are you on?

**Comment by waqas-334** [comment]
Did you also include the Facebook SDK or the adapter will do it automatically?

**Comment by chauduyphanvu** [comment]
@waqas-334, mediation SDKs are fetched transitively via the adapters. Facebook example: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/master/Facebook/build.gradle.kts#L50-L57.

**Comment by kruguerjo** [comment]
> ```
>     implementation("com.applovin.mediation:facebook-adapter:6.8.0.7")
>     
>      java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
>         at com.facebook.ads.internal.util.common.ANActivityLifecycleCallbacksListener.registerActivityCallbacks(ANActivityLifecycleCallbacksListener.java:70)
>         at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:95)
>         at java.lang.Thread.run(Thread.java:923)
> ```
> 
> After integrating applovin facebook mediation adapter, started to face this error

I'm having the same issue:

com.facebook.ads.internal.util.common.ANActivityLifecycleCallbacksListener.registerActivityCallbacks (ANActivityLifecycleCallbacksListener.java:70)
at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run (DynamicLoaderFactory.java:95)
at java.lang.Thread.run (Thread.java:929)

**Comment by santoshbagadi** [comment]
Hi @kruguerjo , what version of Facebook Mediation adapter are you using? The issue should be fixed in `v6.8.0.8` of our Facebook Mediation adapter. 


Are you able to reproduce the issue locally, if so, could you please provide [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) of the full session when the issue is happening
