### ISSUE TITLE
InitSdk crash

### ISSUE THREAD

**Issue by wuaoke** [AppLovin/AppLovin-MAX-SDK-Android#147]
Caused by: java.lang.NullPointerException: 
  at com.applovin.impl.sdk.m.ao (Unknown Source:4)
  at com.applovin.impl.sdk.o.C (Unknown Source:10)
  at com.applovin.impl.sdk.o.a (Unknown Source:180)
  at com.applovin.impl.sdk.o.s (Unknown Source:384)
  at com.applovin.impl.sdk.o.<init> (Unknown Source:33)
  at com.applovin.impl.sdk.m.a (Unknown Source:148)
  at com.applovin.sdk.AppLovinSdk.a (Unknown Source:143)
  at com.applovin.sdk.AppLovinSdk.getInstance (Unknown Source)
  at com.applovin.sdk.AppLovinSdk.getInstance (Unknown Source:14)
  at com.applovin.sdk.AppLovinSdk.getInstance (Unknown Source:5)
  at com.myicon.themeiconchanger.MyIconGPApplication.b (SourceFile:16)
  at i6.d.a (SourceFile:5)
  at i6.d.onCreate (SourceFile:15)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1195)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7202)

 When I call this method “AppLovinSdk.getInstance(context).setMediationProvider("max");”  report this crash

**Comment by wuaoke** [comment]
applovin version:11.1.0

**Comment by thomasmso** [comment]
Hi @wuaoke - Thanks for reporting this, it's likely due to an edge case of passing in a non-Activity context. The issue will be resolved in the next SDK release, I'll notify this thread when that happens.

**Comment by wuaoke** [comment]
Can't use application to initialize applovin?

**Comment by thomasmso** [comment]
You can, but this seems to be an edge case from passing in a non-Activity context, and will be resolved in the next SDK release.

**Comment by thomasmso** [comment]
We just released v11.1.1 with the fix, thanks once again for the valuable feedback!

**Comment by radhasharma123** [comment]
Hi ,
I am using Applovin max sdk.
But with live ads i am not able to show live ads still showing test ad.
Please help to provide any answer why this is going on.

**Comment by santoshbagadi** [comment]
Hi @radhasharma123 , could you please double check that your device ID is still not listed as the [test device on our dashboard](https://monetization-support.applovin.com/hc/en-us/articles/115000509267-How-can-I-get-test-ads-).

**Comment by hani09876** [comment]
Does the applovin.getinstance( unknown) problem solved?

**Comment by ucf0709** [comment]
I think not, i'm still getting this errors
com.applovin.sdk.AppLovinSdk.a(Unknown Source:105), 
com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:0), 
com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:14), 
com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:5), 
com.applovin.sdk.AppLovinSdk.initializeSdk(Unknown Source:2

**Comment by hani09876** [comment]
> I think not, i'm still getting this errors
> com.applovin.sdk.AppLovinSdk.a(Unknown Source:105), 
> com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:0), 
> com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:14), 
> com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:5), 
> com.applovin.sdk.AppLovinSdk.initializeSdk(Unknown Source:2

Did you tried ironsource.

**Comment by santoshbagadi** [comment]
Hi @hani09876 , @ucf0709 the issue should be fixed in v11.1.1 of our SDK. If you are still seeing the issue after upgrading to the latest SDK, could you please share the full stacktrace and if you are able to reproduce the crash locally, [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) will be really helpful.

**Comment by hani09876** [comment]
But i don't know how to upgrade your sdk. Can i connect with you in discord or Twitter?

**Comment by hani09876** [comment]
> Hi @hani09876 , @ucf0709 the issue should be fixed in v11.1.1 of our SDK. If you are still seeing the issue after upgrading to the latest SDK, could you please share the full stacktrace and if you are able to reproduce the crash locally, [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) will be really helpful.

Will you please create a plugin for godot game engine. You have a plugin for unity but not for godot. This is so bad.

**Comment by santoshbagadi** [comment]
@hani09876 we are pretty stacked right now, but we'll look into providing support for Godot in the future. 

Could you please share links to your app(s) on Play/App store?

**Comment by hani09876** [comment]
> @hani09876 we are pretty stacked right now, but we'll look into providing support for Godot in the future. 
> 
> Could you please share links to your app(s) on Play/App store?

https://play.google.com/store/apps/details?id=com.hanif.puzzle


How much time should we wait for godot support
