### ISSUE TITLE
Facebook Native Ads icon not visible in native banner ads and ads not clickable

### ISSUE THREAD

**Issue by maxakash** [AppLovin/AppLovin-MAX-SDK-Android#174]
I have enabled native banner ads for Facebook and upgraded my Facebook adapter to 6.8.0.9 and AppLovin sdk to 11.1.2.
But now native banner ads icon is not visible and the ads are not clickable.

I have not added MediaContentView as it is not required for native banner ads.
Here is the loaded ad 

![WhatsApp Image 2022-02-17 at 10 54 19 AM](https://user-images.githubusercontent.com/17406944/154411091-a0c37c0e-76e5-4ed2-96de-0c79bc711b49.jpeg)

Here is the logcat 
```
D/AppLovinSdk: [MediationAdapterManager] Loaded FACEBOOK_NETWORK
I/AppLovinSdk: [MediationAdapterInitializationManager] Initializing adapter SignalProviderSpec{adObject={"name":"FACEBOOK_NETWORK","server_parameters":{"placement_ids":["236216368252151_236216478252140"]},"class":"com.applovin.mediation.adapters.FacebookMediationAdapter","adapter_timeout_ms":30000,"max_signal_length":32768,"scode":"2!455494.1645075546991!xJ7gY0Q9l9BDJyhaaGbBZ2UViCloRh1yFFYRE6xzCNo*","run_on_ui_thread":false}}
D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: running initialize...
D/AppLovinSdk: [MediationAdapterWrapper] Initializing FacebookMediationAdapter on thread: Thread[AsyncTask #12,5,main] with 'run_on_ui_thread' value: false
I/AppLovinSdk: [FacebookMediationAdapter] Facebook attempted initialization already - marking initialization as completed
D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: finished initialize
D/AppLovinSdk: [MediationService] Collecting signal for adapter: FACEBOOK_NETWORK
D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: running collect_signal...
I/AppLovinSdk: [FacebookMediationAdapter] Collecting signal...
D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: finished collect_signal
D/AppLovinSdk: [TaskCollectSignals] Collected signal from SignalProviderSpec{adObject={"name":"FACEBOOK_NETWORK","server_parameters":{"placement_ids":["236216368252151_236216478252140"]},"class":"com.applovin.mediation.adapters.FacebookMediationAdapter","adapter_timeout_ms":30000,"max_signal_length":32768,"scode":"2!455494.1645075546991!xJ7gY0Q9l9BDJyhaaGbBZ2UViCloRh1yFFYRE6xzCNo*","run_on_ui_thread":false}}
D/AppLovinSdk: [TaskProcessMediationWaterfall:23f741f42327c3ba:NATIVE] Loading ad 1 of 1: FACEBOOK_NATIVE_BIDDING
D/AppLovinSdk: [MediationService] Loading MediatedAd{thirdPartyAdPlacementId=236216368252151_236216478252140, adUnitId=23f741f42327c3ba, format=NATIVE, networkName='Facebook'}...
D/AppLovinSdk: [CommunicatorService] Sending "max_ad_events" message: Bundle[{network_placement=236216368252151_236216478252140, third_party_ad_placement_id=236216368252151_236216478252140, creative_id=3355579587499135938, network_name=FACEBOOK_NATIVE_BIDDING, id=04648d3e71fdb7438c86401edb42319d9bc9a43d, type=WILL_LOAD, ad_format=NATIVE, max_ad_unit_id=23f741f42327c3ba}]
D/AppLovinSdk: [MediationAdapterManager] Loaded FACEBOOK_NATIVE_BIDDING
D/AppLovinSdk: [MediationAdapterManager] Loaded FACEBOOK_NATIVE_BIDDING
I/AppLovinSdk: [MediationAdapterInitializationManager] Initializing adapter MediatedAd{thirdPartyAdPlacementId=236216368252151_236216478252140, adUnitId=23f741f42327c3ba, format=NATIVE, networkName='Facebook'}
D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: running initialize...
D/AppLovinSdk: [MediationAdapterWrapper] Initializing FacebookMediationAdapter on thread: Thread[AsyncTask #12,5,main] with 'run_on_ui_thread' value: false
I/AppLovinSdk: [FacebookMediationAdapter] Facebook attempted initialization already - marking initialization as completed
D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: finished initialize
D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: running load_ad...
I/AppLovinSdk: [FacebookMediationAdapter] Loading native banner ad: 236216368252151_236216478252140...
D/AppLovinSdk: [MediationAdapterWrapper] Setting timeout 10000ms. for MediatedAd{thirdPartyAdPlacementId=236216368252151_236216478252140, adUnitId=23f741f42327c3ba, format=NATIVE, networkName='Facebook'}
D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: finished load_ad
I/AppLovinSdk: [FacebookMediationAdapter] Native ad successfully downloaded media: 236216368252151_236216478252140
I/AppLovinSdk: [FacebookMediationAdapter] Native ad loaded: 236216368252151_236216478252140
I/AppLovinSdk: [FacebookMediationAdapter] Adding native ad icon (https://scontent.fdel1-5.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p130x130/95883653_3122462734479197_7932160999157661696_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=dfded1&_nc_ohc=xZ5yiZRIsioAX94Tsch&_nc_ht=scontent.fdel1-5.fna&oh=00_AT8othfqO55sr0D3wBH24sPvyGQ_URYA990FehTJd_2fIQ&oe=6233B260) to queue to be fetched
I/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: native ad loaded with extra info: null
D/AppLovinSdk: [CommunicatorService] Sending "max_ad_events" message: Bundle[{network_placement=236216368252151_236216478252140, third_party_ad_placement_id=236216368252151_236216478252140, creative_id=3355579587499135938, network_name=FACEBOOK_NATIVE_BIDDING, id=04648d3e71fdb7438c86401edb42319d9bc9a43d, type=DID_LOAD, ad_format=NATIVE, max_ad_unit_id=23f741f42327c3ba}]
D/AppLovinSdk: [MediationWaterfallWinnerTracker] Tracking winning ad: MediatedAd{thirdPartyAdPlacementId=236216368252151_236216478252140, adUnitId=23f741f42327c3ba, format=NATIVE, networkName='Facebook'}
I/AppLovinSdk: [TaskProcessMediationWaterfall:23f741f42327c3ba:NATIVE] Waterfall loaded in 1594ms for FACEBOOK_NATIVE_BIDDING
I/System.out: waterfall is MaxAdWaterfallInfo{name=Default Waterfall, testName=Control, networkResponses=[MaxResponseInfo{adLoadState=AD_LOADED, mediatedNetwork=MaxMediatedNetworkInfo{name=Facebook, adapterClassName=com.applovin.mediation.adapters.FacebookMediationAdapter, adapterVersion=6.8.0.9, sdkVersion=6.8.0}, credentials=Bundle[{placement_ids=[236216368252151_236216478252140], encrypted_cpm=ARGlMoo1Y8WWANphHb5A6vbSdzcrj0nt3rZfIqm8T42LHN5Dt7Ez2TcVsSArnHRyhXpAWexZvuMTqPpCtFyeAcxLcpB2v-qa51Ke_ggWNPkb5sSWMI5Aog, placement_id=236216368252151_236216478252140, is_native_banner=true}], latencyMillis=1592]], latencyMillis=1594} 
D/AppLovinSdk: [CommunicatorService] Sending "max_ad_events" message: Bundle[{network_placement=236216368252151_236216478252140, third_party_ad_placement_id=236216368252151_236216478252140, creative_id=3355579587499135938, network_name=FACEBOOK_NATIVE_BIDDING, id=04648d3e71fdb7438c86401edb42319d9bc9a43d, type=WILL_DISPLAY, ad_format=NATIVE, max_ad_unit_id=23f741f42327c3ba}]


```

**Comment by maxakash** [comment]
Update:
If I ad MediaContentView to the native ad, the ad is clickable but icon is still not loading.
But MediaContentView is not required for native banner ad.
Please look into this @thomasmso

**Comment by tiandrew** [comment]
Hey @maxakash, we've pushed new FB adapters that should fix the issue.

**Comment by maxakash** [comment]
Hey @tiandrew the icon is now rendering but without adding MediaContentView, this add is still not clickable.
"MediaContentView" is not required for Facebook Native Banner ads.

This is getting very frustrating , you guys push updates without even properly testing it.


@thomasmso Please look into this.

**Comment by tiandrew** [comment]
@maxakash apologies for the inconvenience. We've pushed out another new version of the Facebook adapters with the fix for the click registration. Please let me know if you run into any further issues. Thank you for bearing with us!

**Comment by maxakash** [comment]
> @maxakash apologies for the inconvenience. We've pushed out another new version of the Facebook adapters with the fix for the click registration. Please let me know if you run into any further issues. Thank you for bearing with us!

Everything seems to work fine.
Thanks for the quick resolution.

**Comment by apshard** [comment]
@tiandrew The fix is not fully correct. The MediaView is not required for native banners but also it's not prohibited. Even the example of native banner implementation on the official page https://developers.facebook.com/docs/audience-network/setting-up/ad-setup/android/native-banner uses MadiaView for rendering icon. This should be available for unification. Say we want to have a few mediation providers in the same ad unit and we need to have MediaView for some providers. So what should we do with the current implementation of the meta adapter? The correct implementation should use ImageView for the icon when it was provided to max native ad or media view if it was provided.

**Comment by apshard** [comment]
So the correct implementation should work for both cases

```
new MaxNativeAdView(new MaxNativeAdViewBinder.Builder(R.layout.native_ad_medium)
                                    .setTitleTextViewId(R.id.native_ad_headline)
                                    .setBodyTextViewId(R.id.native_ad_body)
                                    .setAdvertiserTextViewId(R.id.native_ad_advertiser)
                                    **.setIconImageViewId(R.id.native_ad_icon)**
                                    .setOptionsContentViewGroupId(R.id.native_ad_options)
                                    .setCallToActionButtonId(R.id.native_ad_cta)
                                    .build(), activity);
```
or

```
new MaxNativeAdView(new MaxNativeAdViewBinder.Builder(R.layout.native_ad_medium)
                                    .setTitleTextViewId(R.id.native_ad_headline)
                                    .setBodyTextViewId(R.id.native_ad_body)
                                    .setAdvertiserTextViewId(R.id.native_ad_advertiser)
                                    **.setMediaContentViewGroupId(R.id.native_ad_media)**
                                    .setOptionsContentViewGroupId(R.id.native_ad_options)
                                    .setCallToActionButtonId(R.id.native_ad_cta)
                                    .build(), activity);
```

**Comment by tiandrew** [comment]
Hi @apshard, if you take a look at our logic just before we call register, we also add the `mediaView` to the clickable views, so you should have no problem including a media view in a Facebook native banner layout as well.

**Comment by apshard** [comment]
@tiandrew but what if we use the template without a view for the icon in our app? And want to render Facebook native banner along with AppLovin and Admob ads using the same unit/template?
```
new MaxNativeAdView(new MaxNativeAdViewBinder.Builder(R.layout.native_ad)
                                    .setTitleTextViewId(R.id.native_ad_headline)
                                    .setBodyTextViewId(R.id.native_ad_body)
                                    .setAdvertiserTextViewId(R.id.native_ad_advertiser)
                                    .setMediaContentViewGroupId(R.id.native_ad_media)
                                    .setOptionsContentViewGroupId(R.id.native_ad_options)
                                    .setCallToActionButtonId(R.id.native_ad_cta)
                                    .build(), activity);
```
As you can see there is no IconImageView and for AppLovin and Admob networks media content will be rendered in media view but for Facebook when the native banner is using Icon should be rendered in the media view in this case (as it works for template native ads).

**Comment by apshard** [comment]
maxNativeAdView.getIconImageView() will be null in this case and null will be passed to registerViewForInteraction

**Comment by tiandrew** [comment]
@apshard ah so you want to use a media view _without_ an icon view for Facebook's native banners. We can accommodate that. Just as a heads up, this change means we will no longer populate both the icon _and_ media view with the icon asset anymore, we only populate the icon if non-null, and media view if the icon is null.

**Comment by apshard** [comment]
@tiandrew Yes, and the proposed solution "populate the icon if non-null, and media view if the icon is null" will work for our needs.

**Comment by apshard** [comment]
> ah so you want to use a media view _without_ an icon view for Facebook's native banners. We can accommodate that. Just as a heads up, this change means we will no longer populate both the icon _and_ media view with the icon asset anymore, we only populate the icon if non-null, and media view if the icon is null.

@tiandrew @maxakash The issue was closed but when will the new version of the adapter with mentioned features be released?

**Comment by maxakash** [comment]
> > ah so you want to use a media view _without_ an icon view for Facebook's native banners. We can accommodate that. Just as a heads up, this change means we will no longer populate both the icon _and_ media view with the icon asset anymore, we only populate the icon if non-null, and media view if the icon is null.
> 
> @tiandrew @maxakash The issue was closed but when will the new version of the adapter with mentioned features be released?

I closed the issue as everything is working for me.

**Comment by tiandrew** [comment]
@apshard we're currently working on a new adapter version that will help with your use-case. This adapter update will likely be released today or tomorrow, I'll update this thread when it's released.

**Comment by tiandrew** [comment]
@apshard the latest version of the Facebook adapter should have your use-case handled. Please let me know if you run into any further issues.
