### ISSUE TITLE
Applovin Max Native Ad Main Image is Missing

### ISSUE THREAD

**Issue by kruguerjo** [AppLovin/AppLovin-MAX-SDK-Android#278]
Hi guys,

 I'm using Facebook bidding with Applovin Max, The native ad main image is missing (see image attached), i'm using medium native ad template. Also there is no native ad impressions in Facebook dashboard, i believe it's because of the Ad main image.
![photo_2022-03-26_20-19-54](https://user-images.githubusercontent.com/102380669/160287438-94990607-f657-43c1-8b3a-c905502baa62.jpg)

**Comment by santoshbagadi** [comment]
Hi @kruguerjo , could you please provide [full verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) of the session where the issue is happening. 

We've also fixed an issue with Facebook native bidding, could you check again today to see if that may have solved your issue as well?

**Comment by kruguerjo** [comment]
> Hi @kruguerjo , could you please provide [full verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) of the session where the issue is happening.
> 
> We've also fixed an issue with Facebook native bidding, could you check again today to see if that may have solved your issue as well?

Hello @santoshbagadi, the issue is still occurring. i'm using medium native ad template, this is the ad unit id : 894415bd856e22fe.

**Comment by santoshbagadi** [comment]
Hi @kruguerjo , in an other thread, you mentioned that you are seeing a crash with Facebook adapter as well. So, could you please provide the verbose logs of the issue as requested above so that we can investigate further.

**Comment by kruguerjo** [comment]
> Hi @kruguerjo , could you please provide [full verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) of the session where the issue is happening.
> 
> We've also fixed an issue with Facebook native bidding, could you check again today to see if that may have solved your issue as well?

The same issue is happening with Applovin native

> @kruguerjo , in an other thread, you mentioned that you are seeing a crash with Facebook adapter as well. So, could you please provide the verbose logs of the issue as requested above so that we can investigate further.

The crash i have mentioned in 'com.facebook.ads.internal.util.common.ANActivityLifecycleCallbacksListener.registerActivityCallbacks
' crash, has been resolved by updating facebook adapter and applovin implementation

**Comment by kruguerjo** [comment]
> Hi @kruguerjo , could you please provide [full verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) of the session where the issue is happening.
> 
> We've also fixed an issue with Facebook native bidding, could you check again today to see if that may have solved your issue as well?

the native is in home activity and nothing appears in the verbose logs

**Comment by santoshbagadi** [comment]
@kruguerjo , could you please double check that verbose logging is enabled. If not, would you be able to provide us a sample project where the issue can be reproduced.

**Comment by kruguerjo** [comment]
where can i send the project

**Comment by kruguerjo** [comment]
> @kruguerjo , could you please double check that verbose logging is enabled. If not, would you be able to provide us a sample project where the issue can be reproduced.

i have seen in another thread that changing, the template from medium to manual will solve the issue, but when i change the template the native ad stop appearing!

**Comment by santoshbagadi** [comment]
@kruguerjo , switching `Template` to `Manual` only works if you are using manual implementation (loading an ad by passing in a `MaxNativeAdView` to `loadAd( MaxNativeAdView )`). If you are using template integration, you should keep `Medium` selected.

**Comment by santoshbagadi** [comment]
@kruguerjo You can send a sample project to santosh.bagadi@applovin.com

**Comment by kruguerjo** [comment]
> @kruguerjo You can send a sample project to [santosh.bagadi@applovin.com](mailto:santosh.bagadi@applovin.com)

Done! this is the email : p******nemodev@gmail.com

**Comment by kruguerjo** [comment]
![Capture](https://user-images.githubusercontent.com/102380669/160448986-78cf7b8a-48f2-4011-9473-0e3f38522aa6.PNG)
also there is no native ad impressions in facebook dashboard
