### ISSUE TITLE
Pangle crash on 12.6.1

### ISSUE THREAD

**Issue by gzjaychen** [AppLovin/AppLovin-MAX-SDK-Android#699]
### MAX SDK Version

12.6.1

### Device/Platform Info

Android

### Current Behavior

Failed to start displaying ad for TIKTOK_BIDDING due to: java.lang.IllegalStateException: Cannot be called in a child thread —— TTRewardVideoAd.showRewardVideoAd

### How to Reproduce

show pangle reward ad

**Comment by NanaAmoah** [comment]
@gzjaychen Thanks for reporting this issue. We have been able to reproduce it and are working on fixing this. I will share updates as they become available.

**Comment by NanaAmoah** [comment]
Hi @gzjaychen, we have released a server-side fix for this issue.

**Comment by stdlam** [comment]
Hi @NanaAmoah I still get this crash on version 12.6.1, could you help check again?

**Comment by NanaAmoah** [comment]
Hi @stdlam, I am not able to reproduce the issue on AppLovin SDK v12.6.1. What Pangle adapter version are you on?
Could you share [full verbose logs of an app session](https://developers.applovin.com/en/max/ios/overview/advanced-settings#enable-verbose-logging) where the issue is reproduced and/or reproduce this in our [demo app](https://github.com/AppLovin/AppLovin-MAX-SDK-Android) and share the project with me?

**Comment by stdlam** [comment]
Hi @NanaAmoah I created a new bug, it also happens on demo app. Could you have check the link below?
https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/710
