### ISSUE TITLE
Admob mediation adapter - initialization problem for interstitial, rewarded and native...

### ISSUE THREAD

**Issue by adnanhaa** [AppLovin/AppLovin-MAX-SDK-Android#87]
I'm getting error in Max mediation debugger when I want to load Admob test ad (interstitial, rewarded and native) for waterfall implementation. Banner and MREC work fine. 

I solve the problem if I call the method MobileAds.initialize(context);. 
Also i tested and this problem does not exist in the previous version - 10.3.5

`D/AppLovinSdk: [MediationAdapterManager] Loaded ADMOB_NETWORK
D/AppLovinSdk: [MediationAdapterWrapper] GoogleMediationAdapter: running load_ad...
I/AppLovinSdk: [GoogleMediationAdapter] Loading interstitial ad: ca-app-pub-3940256099942544/1033173712...`

**E/AppLovinSdk: [MediationAdapterWrapper] Failed start loading MediatedAd{thirdPartyAdPlacementId=ca-app-pub-3940256099942544/1033173712, adUnitId=test_mode_interstitial, format=INTER, networkName='Google AdMob'} : java.lang.IllegalStateException: MobileAds.initialize() must be called prior to setting app muted state.**

`I/AppLovinSdk: [MediationAdapterWrapper] Marking GoogleMediationAdapter as disabled due to: load_ad
E/AppLovinSdk: [MediationAdapterManager] Adding com.applovin.mediation.adapters.GoogleMediationAdapter to list of disabled adapters.
D/AppLovinSdk: [MediationAdapterWrapper] Setting timeout 30000ms. for MediatedAd{thirdPartyAdPlacementId=ca-app-pub-3940256099942544/1033173712, adUnitId=test_mode_interstitial, format=INTER, networkName='Google AdMob'}
D/AppLovinSdk: [MediationAdapterWrapper] GoogleMediationAdapter: finished load_ad
I/AppLovinSdk: [MediationService] Destroying MediatedAd{thirdPartyAdPlacementId=ca-app-pub-3940256099942544/1033173712, adUnitId=test_mode_interstitial, format=INTER, networkName='Google AdMob'}
D/AppLovinSdk: [TaskProcessMediationWaterfall:test_mode_interstitial:INTER] Ad failed to load in 26 ms with error: MaxError{code=-1, message='Failed start loading MediatedAd{thirdPartyAdPlacementId=ca-app-pub-3940256099942544/1033173712, adUnitId=test_mode_interstitial, format=INTER, networkName='Google AdMob'} : java.lang.IllegalStateException: MobileAds.initialize() must be called prior to setting app muted state.'}`

**I/AppLovinSdk: [TaskProcessMediationWaterfall:test_mode_interstitial:INTER] Waterfall failed in 28ms with error: MaxError{code=-5001, message='MAX returned eligible ads from mediated networks, but all ads failed to load. Inspect getWaterfall() for more info.'}**

`D/AppLovinSdk: [MaxInterstitialAd] Transitioning from LOADING to IDLE...`

**Comment by adnanhaa** [comment]
It was 20.5.0.5
I tried other versions but they do not work with sdk 11.0.0. 
(it works with sdk 10.3.5)

I looked at the code of Adapter and the initialization in the latest versions is almost the same.
From version >20.5.0.0 only the callback parameter is changed... 
probably the problem is there where initialisation is called from

Error is: **MobileAds.initialize() must be called prior to setting app muted state.**, 
Is method of GoogleMediationAdapter **loadInterstitialAd** (with updateMuteState) called before initializationin...

SDK cannot load Admob interstitial and rewarded ads (waterfol implementation) but it can banner and mrec. 
Also there is no problem with other networks.
I tested it with Mediation debugger and Test device (IDFA) and I got the same error -5001

**Comment by tiandrew** [comment]
Hey @adnanhaa, can you double check that you have initialized our SDK using `AppLovinSdk.getInstance( this ).initializeSdk()`? Looks like the google adapter has not been initialized, which should happen when you initialize our SDK.

**Comment by adnanhaa** [comment]
yes I did. I already wrote that banners and other networks work properly (and with sdk v10.3.5)... that means initialization is ok. 
The only problem is interstitial and rewarded ads. 
i tried just about everything, spent a lot of time finding out where the problem is. 
I wish I was wrong somewhere but I think this could be a serious problem for anyone using admob 
for both waterfall and bidding (the adapter is the same for both if I noticed correctly?)

I followed this link
https://dash.applovin.com/documentation/mediation/android/getting-started/integration

in my experience I believe that I have to do this only in the initial/main activity. 

everything works fine, everything is ok in the debugger, only the load for these two is not ok
has any of your testers tested this?

**Comment by tiandrew** [comment]
Hi @adnanhaa, could you send me the verbose logs for your app's session in which you're seeing these errors? My email is andrew.tian@applovin.com. You can find the steps for verbose logging here: https://dash.applovin.com/documentation/mediation/android/getting-started/advanced-settings#enable-verbose-logging

**Comment by DmitriyBushuev** [comment]
Same issue, actual not only for AdMob, but for all adapters - no **initialize** method call for the networks adapters. On 10.3.5 version everything is fine.

**Comment by tiandrew** [comment]
Hey @adnanhaa and @DmitriyBushuev, we've identified the problem and are rolling out a backend fix, I'll update the thread when the change has fully propagated.

**Comment by tiandrew** [comment]
Hey @adnanhaa and @DmitriyBushuev, the fix has been deployed, please let me know if you encounter any further issues.

**Comment by DmitriyBushuev** [comment]
@tiandrew As I can see - test mode still doesn't work, adapters doesn't initialize on start. Live ad works correctly.

**Comment by maximilianbuck** [comment]
We deployed a final fix related to adapters not initializing in test mode yesterday. Test mode should no longer have any initialization issues.
